// <auto-generated />
using System;
using InventoryService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InventoryService.Infrastructure.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260307114957_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventoryService.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("Products", "inventory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Name = "Wireless Mouse",
                            Price = 29.99m,
                            ReservedQuantity = 0,
                            Sku = "WM-001",
                            StockQuantity = 100,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            Name = "Mechanical Keyboard",
                            Price = 89.99m,
                            ReservedQuantity = 0,
                            Sku = "MK-001",
                            StockQuantity = 100,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            Name = "USB-C Hub",
                            Price = 49.99m,
                            ReservedQuantity = 0,
                            Sku = "UH-001",
                            StockQuantity = 100,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("a4444444-4444-4444-4444-444444444444"),
                            Name = "Monitor Stand",
                            Price = 39.99m,
                            ReservedQuantity = 0,
                            Sku = "MS-001",
                            StockQuantity = 100,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("a5555555-5555-5555-5555-555555555555"),
                            Name = "Webcam HD",
                            Price = 59.99m,
                            ReservedQuantity = 0,
                            Sku = "WC-001",
                            StockQuantity = 100,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-111111111111"),
                            Name = "Gaming Headset",
                            Price = 79.99m,
                            ReservedQuantity = 0,
                            Sku = "GH-001",
                            StockQuantity = 10,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            Name = "Ergonomic Chair",
                            Price = 299.99m,
                            ReservedQuantity = 0,
                            Sku = "EC-001",
                            StockQuantity = 10,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("b3333333-3333-3333-3333-333333333333"),
                            Name = "Desk Lamp",
                            Price = 34.99m,
                            ReservedQuantity = 0,
                            Sku = "DL-001",
                            StockQuantity = 10,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111111"),
                            Name = "Limited Edition Tablet",
                            Price = 999.99m,
                            ReservedQuantity = 0,
                            Sku = "LT-001",
                            StockQuantity = 1,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("d1111111-1111-1111-1111-111111111111"),
                            Name = "Discontinued Cable",
                            Price = 9.99m,
                            ReservedQuantity = 0,
                            Sku = "DC-001",
                            StockQuantity = 0,
                            Version = 0u
                        });
                });

            modelBuilder.Entity("InventoryService.Domain.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Reservations", "inventory");
                });

            modelBuilder.Entity("Shared.Infrastructure.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key", "OperationType")
                        .IsUnique();

                    b.ToTable("IdempotencyRecords", "inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
